### ISSUE TITLE
Helm installation does not work for OCP 4.4 (Kubernetes 1.17)

### ISSUE THREAD

**Issue by sglover** [IBM/openstack-vim-driver#62]
Helm installation fails with the following error:

```
helm install os-vim-driver-2.1.0a2.issue51.tgz --name os-vim-driver --namespace lifecycle-manager -f custom-values.yml --tls --tiller-namespace $CS_NAMESPACE
Error: validation failed: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"
```

because OCP 4.4 is using a newer version of Kubernetes (1.17) and the Deployments and Statefulsets apiVersion changed from extensions/v1beta1 to apps/v1. The driver Helm chart needs to be updated to account for this e.g. by using
Capabilities.KubeVersion.Major and Capabilities.KubeVersion.Minor (see https://helm.sh/docs/chart_template_guide/builtin_objects/) to switch between the different apiVersions.

**Comment by visomwa1** [comment]
We tried a workaround to changing the api version from extensions to apps/v1 in templates/deployment.yaml and templates/ingress.yaml file and created the chart and tried installation but still getting failed with below error :

(lmctl-env) [root@puneteam-ocp44-ha5-inf vimdriver]# helm install os-vim-driver-2.1.0a2.issue51.tgz --name os-vim-driver --namespace lifecycle-manager -f custom-values.yml --tls --tiller-namespace $CS_NAMESPACE
Error: validation failed: unable to recognize "": no matches for kind "Ingress" in version "apps/v1"

**Comment by visomwa1** [comment]
now i am getting this error 
(lmctl-env) [root@puneteam-ocp44-ha5-inf vimdriver]# helm install os-vim-driver-2.1.0a2.issue51.tgz --name os-vim-driver --namespace lifecycle-manager -f custom-values.yml --tls --tiller-namespace $CS_NAMESPACE
Error: release os-vim-driver failed: Deployment.apps "os-vim-driver" is invalid: [spec.selector: Required value, spec.template.metadata.labels: Invalid value: map[string]string{"app":"os-vim-driver", "part-of":"lm"}: selector does not match template labels]

**Comment by dvaccarosenna** [comment]
In later versions of Kubernetes deployments I think you need to explicitly add the labels as selectors (so they match):
So the deployment.yaml file needs:
```
spec:
  selector: # This is the new bit
    matchLabels:
      app: os-vim-driver
  template: # Template remains as it is
    metadata:
      labels:
        app: os-vim-driver
        part-of: lm
    spec:
```

**Comment by dasuresh** [comment]
Thanks @dvaccarosenna , we have installed as per instruction and its getting deployed now.

**Comment by sglover** [comment]
We need support for Kubernetes 1.13 onwards (to allow it to run in e.g. AIO as well as OCP) so some kind of switch could be used here e.g. by using
Capabilities.KubeVersion.Major and Capabilities.KubeVersion.Minor (see https://helm.sh/docs/chart_template_guide/builtin_objects/) to switch between the different apiVersions.

**Comment by owen-lynch-ibm** [comment]
> We need support for Kubernetes 1.13 onwards (to allow it to run in e.g. AIO as well as OCP) so some kind of switch could be used here e.g. by using
> Capabilities.KubeVersion.Major and Capabilities.KubeVersion.Minor (see https://helm.sh/docs/chart_template_guide/builtin_objects/) to switch between the different apiVersions.

I made changes and tested on my AIO system (K8s 1.13) and it works as changed via PR openstack-vim-driver/pull/64 
Also installs  on OCP 4.5
